### ISSUE TITLE
load Test N:N,  publish 100 people, subscribe 100 people, how to ?

### ISSUE THREAD

**Issue by daekyocnslab** [OpenVidu/openvidu-loadtest#10]
hi, we are openvidu pro user,

We want to provide a service with 100 simultaneous access (publish/subscribe)
I want to check it with a load test, but please tell me how

1. Test Setting
    browser-emulator , AWS, c5.xlarge X 20EA
    OVP 2.17.1, AWS, c5.2xlarge, 1EA
    KMS: AWS, c5.2xlarge, 1EA

2. Test cases
--> paricipants values changed[1~5]
{
        "testcases": [
                {
                        "typology": "N:N",
                        "participants": [5],
                        "sessions": 1,
                        "browserMode": "EMULATE",
                        "recording": false,
                        "headless": false
                }
        ]
}

3. current situation
I can't pass 30 connections.

![스크린샷 2021-05-10 오후 4 20 48](https://user-images.githubusercontent.com/36141397/117621935-0ff36500-b1ad-11eb-80b0-ffb374048582.png)

4. load-test log
2021-05-10 07:17:37.936  INFO 4316 --- [           main] i.o.l.controller.LoadTestController      : Starting session 'LoadTestSession1'
2021-05-10 07:17:37.936  INFO 4316 --- [           main] i.o.l.controller.LoadTestController      : Creating PUBLISHER 'S9_User1' in session
2021-05-10 07:17:37.936  INFO 4316 --- [           main] i.o.l.i.BrowserEmulatorClient            : Selected worker: https://localhost:5000
2021-05-10 07:17:48.558 ERROR 4316 --- [           main] i.o.l.i.BrowserEmulatorClient            : Error. Http Status Response 500 
2021-05-10 07:17:48.558 ERROR 4316 --- [           main] i.o.l.i.BrowserEmulatorClient            : Response message {"error":{"message":"Error on publishVideo: {\"stack\":\"Error: Request has timed out\\n    at Timeout.timeout (/home/ubuntu/openvidu-loadtest/browser-emulator/node_modules/openvidu-browser/lib/OpenViduInternal/KurentoUtils/kurento-jsonrpc/index.js:385:29)\\n    at listOnTimeout (internal/timers.js:554:17)\\n    at processTimers (internal/timers.js:497:7)\",\"message\":\"Request has timed out\",\"request\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"publishVideo\\\",\\\"params\\\":{\\\"doLoopback\\\":false,\\\"hasAudio\\\":true,\\\"hasVideo\\\":true,\\\"audioActive\\\":true,\\\"videoActive\\\":true,\\\"typeOfVideo\\\":\\\"CUSTOM\\\",\\\"frameRate\\\":-1,\\\"videoDimensions\\\":\\\"{\\\\\\\"width\\\\\\\":640,\\\\\\\"height\\\\\\\":480}\\\",\\\"sdpOffer\\\":\\\"v=0\\\\r\\\\no=- 2269671747360611720 2 IN IP4 127.0.0.1\\\\r\\\\ns=-\\\\r\\\\nt=0 0\\\\r\\\\na=group:BUNDLE 0 1\\\\r\\\\na=msid-semantic: WMS d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62\\\\r\\\\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\\\\r\\\\nc=IN IP4 0.0.0.0\\\\r\\\\na=rtcp:9 IN IP4 0.0.0.0\\\\r\\\\na=ice-ufrag:FACQ\\\\r\\\\na=ice-pwd:B8C0M705YRaDQ78oDN4yJHpR\\\\r\\\\na=ice-options:trickle\\\\r\\\\na=fingerprint:sha-256 C3:71:27:01:D7:0D:14:3C:01:17:98:8F:DD:C9:35:AA:9A:66:7F:BB:89:61:C9:AD:87:B1:BC:58:1B:24:B5:06\\\\r\\\\na=setup:actpass\\\\r\\\\na=mid:0\\\\r\\\\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\\\\r\\\\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\\\\r\\\\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\\\\r\\\\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\\\\r\\\\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\\\\r\\\\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\\\\r\\\\na=sendonly\\\\r\\\\na=msid:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62 f6db0b42-9683-456e-afaa-9e22eeceb5d3\\\\r\\\\na=rtcp-mux\\\\r\\\\na=rtpmap:111 opus/48000/2\\\\r\\\\na=rtcp-fb:111 transport-cc\\\\r\\\\na=fmtp:111 minptime=10;useinbandfec=1\\\\r\\\\na=rtpmap:103 ISAC/16000\\\\r\\\\na=rtpmap:104 ISAC/32000\\\\r\\\\na=rtpmap:9 G722/8000\\\\r\\\\na=rtpmap:102 ILBC/8000\\\\r\\\\na=rtpmap:0 PCMU/8000\\\\r\\\\na=rtpmap:8 PCMA/8000\\\\r\\\\na=rtpmap:106 CN/32000\\\\r\\\\na=rtpmap:105 CN/16000\\\\r\\\\na=rtpmap:13 CN/8000\\\\r\\\\na=rtpmap:110 telephone-event/48000\\\\r\\\\na=rtpmap:112 telephone-event/32000\\\\r\\\\na=rtpmap:113 telephone-event/16000\\\\r\\\\na=rtpmap:126 telephone-event/8000\\\\r\\\\na=ssrc:3530838417 cname:GAW0zntdlUbLrIwx\\\\r\\\\na=ssrc:3530838417 msid:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62 f6db0b42-9683-456e-afaa-9e22eeceb5d3\\\\r\\\\na=ssrc:3530838417 mslabel:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62\\\\r\\\\na=ssrc:3530838417 label:f6db0b42-9683-456e-afaa-9e22eeceb5d3\\\\r\\\\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\\\\r\\\\nc=IN IP4 0.0.0.0\\\\r\\\\na=rtcp:9 IN IP4 0.0.0.0\\\\r\\\\na=ice-ufrag:FACQ\\\\r\\\\na=ice-pwd:B8C0M705YRaDQ78oDN4yJHpR\\\\r\\\\na=ice-options:trickle\\\\r\\\\na=fingerprint:sha-256 C3:71:27:01:D7:0D:14:3C:01:17:98:8F:DD:C9:35:AA:9A:66:7F:BB:89:61:C9:AD:87:B1:BC:58:1B:24:B5:06\\\\r\\\\na=setup:actpass\\\\r\\\\na=mid:1\\\\r\\\\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\\\\r\\\\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\\\\r\\\\na=extmap:13 urn:3gpp:video-orientation\\\\r\\\\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\\\\r\\\\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\\\\r\\\\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\\\\r\\\\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\\\\r\\\\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\\\\r\\\\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\\\\r\\\\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\\\\r\\\\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\\\\r\\\\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\\\\r\\\\na=sendonly\\\\r\\\\na=msid:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62 6eda7daa-0881-43d5-bdc2-c60dcd97724c\\\\r\\\\na=rtcp-mux\\\\r\\\\na=rtcp-rsize\\\\r\\\\na=rtpmap:96 VP8/90000\\\\r\\\\na=rtcp-fb:96 goog-remb\\\\r\\\\na=rtcp-fb:96 transport-cc\\\\r\\\\na=rtcp-fb:96 ccm fir\\\\r\\\\na=rtcp-fb:96 nack\\\\r\\\\na=rtcp-fb:96 nack pli\\\\r\\\\na=rtpmap:97 rtx/90000\\\\r\\\\na=fmtp:97 apt=96\\\\r\\\\na=rtpmap:98 VP9/90000\\\\r\\\\na=rtcp-fb:98 goog-remb\\\\r\\\\na=rtcp-fb:98 transport-cc\\\\r\\\\na=rtcp-fb:98 ccm fir\\\\r\\\\na=rtcp-fb:98 nack\\\\r\\\\na=rtcp-fb:98 nack pli\\\\r\\\\na=fmtp:98 profile-id=0\\\\r\\\\na=rtpmap:99 rtx/90000\\\\r\\\\na=fmtp:99 apt=98\\\\r\\\\na=rtpmap:100 VP9/90000\\\\r\\\\na=rtcp-fb:100 goog-remb\\\\r\\\\na=rtcp-fb:100 transport-cc\\\\r\\\\na=rtcp-fb:100 ccm fir\\\\r\\\\na=rtcp-fb:100 nack\\\\r\\\\na=rtcp-fb:100 nack pli\\\\r\\\\na=fmtp:100 profile-id=2\\\\r\\\\na=rtpmap:101 rtx/90000\\\\r\\\\na=fmtp:101 apt=100\\\\r\\\\na=rtpmap:127 red/90000\\\\r\\\\na=rtpmap:124 rtx/90000\\\\r\\\\na=fmtp:124 apt=127\\\\r\\\\na=rtpmap:125 ulpfec/90000\\\\r\\\\na=ssrc-group:FID 1340715782 9938367\\\\r\\\\na=ssrc:1340715782 cname:GAW0zntdlUbLrIwx\\\\r\\\\na=ssrc:1340715782 msid:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62 6eda7daa-0881-43d5-bdc2-c60dcd97724c\\\\r\\\\na=ssrc:1340715782 mslabel:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62\\\\r\\\\na=ssrc:1340715782 label:6eda7daa-0881-43d5-bdc2-c60dcd97724c\\\\r\\\\na=ssrc:9938367 cname:GAW0zntdlUbLrIwx\\\\r\\\\na=ssrc:9938367 msid:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62 6eda7daa-0881-43d5-bdc2-c60dcd97724c\\\\r\\\\na=ssrc:9938367 mslabel:d89952ef-e4e6-41f6-b5b7-88ef4e5e4d62\\\\r\\\\na=ssrc:9938367 label:6eda7daa-0881-43d5-bdc2-c60dcd97724c\\\\r\\\\n\\\"},\\\"id\\\":39}\",\"requestTime\":1620631058531}"}} 
2021-05-10 07:17:48.558 ERROR 4316 --- [           main] i.o.l.controller.LoadTestController      : Response status is not 200 OK. Exit

**Comment by micaelgallego** [comment]
First of all, it is important to note that 100 videos can not be played in a browser in a standard PC. 

So it is not possible to create a session with 100 participants where all participants are viewing to other 99 participants. The limit here is the browser, not OpenVidu.

On the other hand, 100 participants means 100x100 = 10000 streams managed by a media server. Currently OpenVidu is not able to split a session in several media servers. So you will need a powerfull media node to manage 10000 streams. A 4 CPU machine is hable to manage around 250/300 audio+video streams. But scalability is not linear and possible you will hit some bottleneck somewhere. 

We are working on several features to improve OpenVidu scalability for big sessions: 
* The ability to split a session between several media nodes. 
* The ability to detect who is speaking in the server side so it is not needed to send all streams to the browser. Only the ones of the speaking people.
* The ability to reduce the CPU load of every stream in the media node using alternative media servers. In that way, more stream density in media nodes means more scalability.

There is not due date for those new features... we expect to have them in 2021Q3.

**Comment by ivchicano** [comment]
Closing because of inactivity
