### ISSUE TITLE
issue on browser-emulator startup

### ISSUE THREAD

**Issue by felix99047** [OpenVidu/openvidu-loadtest#34]
Hi OpenVidu team,
I am trying to use openvidu-loadtest, when I launch browser-emulator by "vagrant up", I found the service could not startup. 5000 and 5001 are not listening, then I checked the crontab.log in the VM as below, could you please help take a look.

> browser-emulator@2.2.0 start:prod-firefox
> EMULATED_USER_TYPE=NONE REAL_DRIVER=firefox node ./dist/server.js

COM_MODULE environment variable is not set. Using default com-module (OpenVidu 2)
Pulling Docker images needed...
(node:1111) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
---------------------------------------------------------

Service started in PRODUCTION mode
Emulated user type: NONE
API REST is listening in port 5000
WebSocket is listening in port 5001

---------------------------------------------------------
node:fs:596
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '/opt/openvidu-loadtest/browser-emulator/stats/connections.json'
    at Object.openSync (node:fs:596:3)
    at Object.writeFileSync (node:fs:2322:35)
    at new BrowserManagerService (/opt/openvidu-loadtest/browser-emulator/dist/services/browser-manager.service.js:29:16)
    at BrowserManagerService.getInstance (/opt/openvidu-loadtest/browser-emulator/dist/services/browser-manager.service.js:34:46)
    at cleanup (/opt/openvidu-loadtest/browser-emulator/dist/server.js:22:76)
    at /opt/openvidu-loadtest/browser-emulator/dist/server.js:98:13
    at /opt/openvidu-loadtest/browser-emulator/node_modules/node-cleanup/node-cleanup.js:57:13
    at Array.forEach (<anonymous>)
    at signalHandler (/opt/openvidu-loadtest/browser-emulator/node_modules/node-cleanup/node-cleanup.js:56:21)
    at process.emit (node:events:517:28) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/openvidu-loadtest/browser-emulator/stats/connections.json'
}

Node.js v18.20.2
=================================
Below is the logs for "vagrant up"

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ivchicano/browseremulator-ov-ff'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ivchicano/browseremulator-ov-ff' version '0.0.1' is up to date...
==> default: Setting the name of the VM: browser-emulator_default_1715853972479_56121
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 5001 (guest) => 5001 (host) (adapter 1)
    default: 5900 (guest) => 5900 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.0.0 r127566
    default: VirtualBox Version: 6.1
==> default: Mounting shared folders...
    default: /vagrant => /opt/openvidu-loadtest/browser-emulator
    default: /opt/openvidu-loadtest/browser-emulator/src => /opt/openvidu-loadtest/browser-emulator/src
    default: /opt/openvidu-loadtest/browser-emulator/stats => /opt/openvidu-loadtest/browser-emulator/stats
    default: /opt/openvidu-loadtest/browser-emulator/public => /opt/openvidu-loadtest/browser-emulator/public
    default: /opt/openvidu-loadtest/browser-emulator/public-lk => /opt/openvidu-loadtest/browser-emulator/public-lk
    default: /opt/openvidu-loadtest/browser-emulator/recordings => /opt/openvidu-loadtest/browser-emulator/recordings
    default: /opt/openvidu-loadtest/browser-emulator/qoe_scripts => /opt/openvidu-loadtest/browser-emulator/qoe_scripts
    default: /opt/openvidu-loadtest/browser-emulator/prepare_scripts => /opt/openvidu-loadtest/browser-emulator/prepare_scripts
    default: /opt/openvidu-loadtest/browser-emulator/recording_scripts => /opt/openvidu-loadtest/browser-emulator/recording_scripts
==> default: Running provisioner: file...
    default: ./package.json => /opt/openvidu-loadtest/browser-emulator/package.json
==> default: Running provisioner: file...
    default: ./download_mediafiles.sh => /opt/openvidu-loadtest/browser-emulator/download_mediafiles.sh
==> default: Running provisioner: file...
    default: ./tsconfig.json => /opt/openvidu-loadtest/browser-emulator/tsconfig.json
==> default: Running provisioner: file...
    default: ./debug_vnc_local.sh => /opt/openvidu-loadtest/browser-emulator/debug_vnc.sh

**Comment by ivchicano** [comment]
Thanks for the report!
Seems like last box update had some problems, we reuploaded it with new bugfixes, you can update it by running
`vagrant box update`
After that, destroy the previous VM if up `vagrant destroy -f` and start it again `vagrant up`.

**Comment by ivchicano** [comment]
Closing because of inactivity
