### ISSUE TITLE
loadtest-controller behavior not normal

### ISSUE THREAD

**Issue by felix99047** [OpenVidu/openvidu-loadtest#36]
Hi Team,
Please help have a look at the below controller logs.
1. Why it always creating participant x in **session 0**?
2. After worker CPU usage reaches to almost 100%,  we will get request timed out exception.
3. It seems like the "src/main/resources/test_cases.json" is not effective. I am using the below test cases configuration.
```
{
        "testcases": [
                {
                        "typology": "N:N",
                        "participants": ["2"],
                        "sessions": "5",
                        "startingParticipants": 2,
                        "browserMode": "REAL",
                        "resolution": "640x480",
                        "recording": false,
                        "headless": false,
                        "description": "This test case will add infinite sessions (until it reaches its limit) of publishers that the array of participants indicates"
                }
        ]
}

```

2024-05-17 09:24:52.510  INFO 1829253 --- [           main] i.openvidu.loadtest.LoadTestApplication  : Started LoadTestApplication in 1.56 seconds (JVM running for 1.946)
2024-05-17 09:24:52.516  INFO 1829253 --- [           main] i.o.l.controller.LoadTestController      : Starting browser estimation
2024-05-17 09:24:52.516  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Pinging to 127.0.0.1 ...
2024-05-17 09:24:52.637  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Ping success. Response Pong
2024-05-17 09:24:52.665  INFO 1829253 --- [           main] i.o.loadtest.services.WebSocketClient    : Websocket connected
2024-05-17 09:24:52.666  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Initialize worker 127.0.0.1
2024-05-17 09:25:28.013  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Selected worker: 127.0.0.1
2024-05-17 09:25:28.013  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Creating participant 0 in session 0
2024-05-17 09:25:50.174  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Connection e4d94c4a-8287-473b-8ca7-e76da698e0aa created
2024-05-17 09:25:50.174  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker CPU USAGE: 86.5%
2024-05-17 09:25:50.175  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker STREAMS PROCESSED: 1
2024-05-17 09:25:50.175  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker PARTICIPANTS: 1
2024-05-17 09:25:50.175  INFO 1829253 --- [           main] i.o.l.controller.LoadTestController      : Waiting 5 seconds because of sleep between participants in estimation
2024-05-17 09:25:55.175  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Selected worker: 127.0.0.1
2024-05-17 09:25:55.176  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Creating participant 1 in session 0
2024-05-17 09:26:08.802  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Connection fb551384-b07d-45e2-ab73-7e5d36d150cd created
2024-05-17 09:26:08.802  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker CPU USAGE: 48.54%
2024-05-17 09:26:08.802  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker STREAMS PROCESSED: 4
2024-05-17 09:26:08.802  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker PARTICIPANTS: 2
2024-05-17 09:26:08.802  INFO 1829253 --- [           main] i.o.l.controller.LoadTestController      : Waiting 5 seconds because of sleep between participants in estimation
2024-05-17 09:26:13.803  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Selected worker: 127.0.0.1
2024-05-17 09:26:13.803  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Creating participant 1 in session 0
2024-05-17 09:26:40.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Connection 53e54921-1b32-4e3c-8b04-1791f24ce7ee created
2024-05-17 09:26:40.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker CPU USAGE: 96.84%
2024-05-17 09:26:40.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker STREAMS PROCESSED: 9
2024-05-17 09:26:40.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Worker PARTICIPANTS: 3
2024-05-17 09:26:40.799  INFO 1829253 --- [           main] i.o.l.controller.LoadTestController      : Waiting 5 seconds because of sleep between participants in estimation
2024-05-17 09:26:45.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Selected worker: 127.0.0.1
2024-05-17 09:26:45.799  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Creating participant 2 in session 0
java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at io.openvidu.loadtest.utils.CustomHttpClient.sendPost(CustomHttpClient.java:73)
        at io.openvidu.loadtest.services.BrowserEmulatorClient.createParticipant(BrowserEmulatorClient.java:284)
        at io.openvidu.loadtest.services.BrowserEmulatorClient.createPublisher(BrowserEmulatorClient.java:180)
        at io.openvidu.loadtest.controller.LoadTestController.estimate(LoadTestController.java:264)
        at io.openvidu.loadtest.controller.LoadTestController.lambda$startLoadTests$13(LoadTestController.java:366)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.openvidu.loadtest.controller.LoadTestController.startLoadTests(LoadTestController.java:319)
        at io.openvidu.loadtest.LoadTestApplication.start(LoadTestApplication.java:42)
        at io.openvidu.loadtest.LoadTestApplication.whenReady(LoadTestApplication.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:312)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:197)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:160)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
        at io.openvidu.loadtest.LoadTestApplication.main(LoadTestApplication.java:34)
2024-05-17 09:27:45.808 ERROR 1829253 --- [           main] i.o.l.controller.LoadTestController      : Response status is not 200 OK. Exiting
2024-05-17 09:27:45.808  INFO 1829253 --- [pool-2-thread-1] i.o.l.services.BrowserEmulatorClient     : Deleting all participants from worker 127.0.0.1
2024-05-17 09:27:48.236  INFO 1829253 --- [pool-2-thread-1] i.o.l.services.BrowserEmulatorClient     : Participants in worker 127.0.0.1 deleted
2024-05-17 09:27:48.237  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Instance 127.0.0.1:5000 is clean
2024-05-17 09:27:48.237  INFO 1829253 --- [           main] i.o.l.services.BrowserEmulatorClient     : Participants disconnected
2024-05-17 09:27:48.237  INFO 1829253 --- [           main] i.o.l.controller.LoadTestController      : Waiting 5 seconds because of Waiting MediaServer recovers his CPU
2024-05-17 09:27:53.237  INFO 1829253 --- [           main] i.openvidu.loadtest.LoadTestApplication  : Finished

**Comment by ivchicano** [comment]
If the MANUAL_PARTICIPANTS_ALLOCATION property in application.properties is set to false, before the test an estimation is made using a single worker to check how many users can a worker have before reaching the CPU threshold in the WORKER_MAX_LOAD property. This estimation uses the session number 0 as a placeholder. After the estimation, the real test begins.

If the estimate returns an error (such as the timeout), it considers the worker faulty, as it cannot distinguish between a faulty worker or an overloaded one, and stops the test.

We recommend using a WORKER_MAX_LOAD lesser than 100, for example 75, to avoid overloading the worker (it shouldn't be the default value, that's a mistake on our part).

**Comment by felix99047** [comment]
The system will throw request time out when the worker CPU USAGE 100%, but from the browser-emulator VM, i can see the CPU not up to 100%, not sure why?
**loadtest-controller logs:**
```
2024-05-20 07:34:35.674  INFO 1841502 --- [pool-3-thread-6] i.o.l.services.BrowserEmulatorClient     : Worker CPU USAGE: 100.0%
2024-05-20 07:34:35.675  INFO 1841502 --- [pool-3-thread-6] i.o.l.services.BrowserEmulatorClient     : Worker STREAMS PROCESSED: 10
2024-05-20 07:34:35.675  INFO 1841502 --- [pool-3-thread-6] i.o.l.services.BrowserEmulatorClient     : Worker PARTICIPANTS: 6
java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at io.openvidu.loadtest.utils.CustomHttpClient.sendPost(CustomHttpClient.java:73)
        at io.openvidu.loadtest.services.BrowserEmulatorClient.createParticipant(BrowserEmulatorClient.java:284)
        at io.openvidu.loadtest.services.BrowserEmulatorClient.createPublisher(BrowserEmulatorClient.java:180)
```
**VM CPU usage via top command:**

```
vagrant@ubuntu-jammy:~$ top
top - 07:34:45 up  3:28,  1 user,  load average: 23.93, 6.93, 2.44
Tasks: 195 total,   8 running, 187 sleeping,   0 stopped,   0 zombie
%Cpu(s): 55.5 us, 35.0 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  9.2 si,  0.0 st
MiB Mem :   7937.6 total,   3737.4 free,   2340.1 used,   1860.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   5157.0 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  27149 vagrant   20   0 3063840 296624 148604 D  31.2   3.6   0:12.95 firefox-bin
  26567 vagrant   20   0 3272248 371784 190692 S  30.2   4.6   0:25.50 firefox-bin
  28459 vagrant   20   0 2602584 169300 105104 S  30.2   2.1   0:05.26 Isolated Web Co
  28391 vagrant   20   0 2603268 167956 105184 S  29.6   2.1   0:06.84 Isolated Web Co
  27150 vagrant   20   0   10.9g 297128 147820 R  29.2   3.7   0:14.50 firefox-bin
  26824 vagrant   20   0 3069556 307368 147616 R  28.2   3.8   0:21.88 firefox-bin
  26568 vagrant   20   0 3278548 365912 188700 R  27.9   4.5   0:26.16 firefox-bin
  27779 vagrant   20   0 2610132 166632 106436 S  27.6   2.1   0:18.90 Isolated Web Co
  27327 vagrant   20   0 2610100 163248 104324 S  27.2   2.0   0:24.48 Isolated Web Co
  27391 vagrant   20   0 2610800 156388  96760 S  26.9   1.9   0:24.44 Isolated Web Co
  28023 vagrant   20   0 2607244 156092  99836 R  26.9   1.9   0:14.59 Isolated Web Co
  26835 vagrant   20   0 3056388 295236 144488 R  26.2   3.6   0:20.30 firefox-bin
   2539 vagrant   20   0   21.0g 160792  50564 R  11.6   2.0   2:40.89 node
```
Questions:
1. Worker CPU usages is different from VM CPU usages?
2. Why firefox-bin and Isolated Web Co occupy so many CPU resources, from my several tests, 4 CPUs only can support 3 sessions. How to optimize this?

Thanks.

**Comment by ivchicano** [comment]
The CPU shown in the loadtest controller is the CPU when the worker responds, just after it creates the browser, so the CPU is at its highest. The CPU of the worker usually stabilizes later to a somewhat lower value, like you see when you use `top`.

For the browsers consuming less resources, first you can set the property QOE_ANALYSIS_RECORDINGS to false if you have it on true. Recording those videos is a very CPU intensive task done in the browser.

You can also reduce the size of the session, sessions with a higher number of publishers consume more resources exponentially.

**Comment by ivchicano** [comment]
Closing because of inactivity
